conditioning:
  method: ps
  params:
    scale: 1

data:
  name: ffhq
  root: ./data/celeba-100/
  #root: data/deblurring_test_set

measurement:
  operator:
    name: kernel_blur
    kernel_path: ./data/kernels/4.npy

  noise: 
    name: gaussian
    sigma: 0.0627 #(8 / 255) * 2 (noise for image in range [-1, 1])