conditioning:
  method: ps
  params:
    scale: 1

data:
  name: ffhq
  root: ./data/celeba-100/
  root: ./data/face_sr_test_set

measurement:
  operator:
    name: super_resolution_blur
    kernel_path: ./data/kernels/4.npy
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

  noise: 
    name: gaussian
    sigma: 0.024 #(3 / 255) * 2 (noise for image in range [-1, 1])